
import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { v4 as uuidv4 } from 'uuid';
import Sidebar from './components/Sidebar';
import ChatInput from './components/ChatInput';
import SettingsModal from './components/SettingsModal';
import UpdatesModal from './components/UpdatesModal';
import ContextMenu from './components/ContextMenu';
import Photosam from './components/Photosam';
import InsightsView from './components/InsightsView';
import EssayComposer from './components/EssayComposer';
import CameraCaptureModal from './components/CameraCaptureModal';
import ImagePreviewModal from './components/ImagePreviewModal';
import MathConsole from './components/MathConsole';
import WelcomeTutorial from './components/WelcomeTutorial';
import StThemeNotification from './components/StThemeNotification';
import InstallNotification from './components/InstallNotification';
import VoiceErrorNotification from './components/VoiceErrorNotification';
import GoogleSignInNotification from './components/GoogleSignInNotification';
import ForcedResetModal from './components/ForcedResetModal';
import PreregistrationModal from './components/PreregistrationModal';
import ChatMessageItem from './components/ChatMessage';
import VoiceOrb from './components/VoiceOrb';
import SamStudios from './components/SamStudios';
import VoxelToyBox from './components/VoxelToyBox';
import LogicLab from './components/LogicLab';
import EchoRealms from './components/EchoRealms';
import ChronoLense from './components/ChronoLense';
import RealityScanner from './components/RealityScanner';
import AdminBroadcast from './components/AdminBroadcast';
import GlobalNotification from './components/GlobalNotification';
import { streamGenerateContent, generateImage, startActiveConversation, detect